### ISSUE TITLE
Exit code should be 0 when querying version?

### ISSUE THREAD

**Issue by cherdt** [simsong/bulk_extractor#102]
When I supply the `-V` flag to bulk_extractor to get the version, the exit code is 1 (indicating an error). I would expect the exit code to be 0.

Actual:

```
# /usr/local/bin/bulk_extractor -V
bulk_extractor 1.5.5
# echo $?
1
```

Expected:

```
# /usr/local/bin/bulk_extractor -V
bulk_extractor 1.5.5
# echo $?
0
```

**Comment by simsong** [comment]
Fixed it 8c872b45b49b48f8ce6f37936f7cfd946eace36f.
