### ISSUE TITLE
No way to verify bulk_extractor downloads from downloads.digitalcorpora.org/downloads

### ISSUE THREAD

**Issue by ghosthound** [simsong/bulk_extractor#108]
I have not found a way to verify bulk_extractor downloads from downloads.digitalcorpora.org.  For example, if one wants to install the pre-built bulk_extractor 1.5.5 for windows, one can download:

http://downloads.digitalcorpora.org/downloads/bulk_extractor/bulk_extractor-1.5.5-windowsinstaller.exe

So far as I can see, the installer is not signed nor is there a list of checksums or signatures available.  As well, it is served over http by default and using https results in receiving a self-certificate for "cfrs.gmu.edu" that expired in March 2012.

It would be great if there was a way to verify what is downloaded.

**Comment by simsong** [comment]
Thanks for the email. Would you feel more comfortable if the downloads.digitalcorpora.org automatically redirected to https://downloads.digitalcorpora.org/ which was signed with a LetsEncrypt certificate?

If you are uncomfortable about the Windows installer, you can always compile it yourself from sources.

**Comment by ghosthound** [comment]
Yes, a valid LetsEncrypt cert would be great.  If you can provide hashes for the downloadable files too that'd be great (good for knowing the download worked right for example).

Actually I am working on building the windows version, I'm interested in seeing how it compares to the pre-built one with different build settings (and yeah, cross-compiling for windows is a pain).

**Comment by simsong** [comment]
I found cross-compiling for windows to be especially easy. If you can tell me how to sign the executables from Linux, I can do that. 
(Actually, we explored this several years ago, but gave up on it.)

**Comment by simsong** [comment]
@ghosthound , can we host your pre-built windows binaries?

**Comment by simsong** [comment]
> @ghosthound , can we host your pre-built windows binaries?

Yes!

**Comment by simsong** [comment]
We now have hash values for the prebuilt installers displayed on the digitalcorpora website and all downloads are by TLS. 

Closing this issue.
