### ISSUE TITLE
New release does not support SSL 1.1

### ISSUE THREAD

**Issue by fxcoudert** [simsong/bulk_extractor#117]
The latest released version does not support OpenSSL 1.1, and the older OpenSSL 1.0 is reaching end of life next month. It would be nice to cut a new release, that includes the latest `dfxml` and therefore supports OpenSSL 1.1

**Comment by simsong** [comment]
I will be making a release this weekend. Any other requests?

**Comment by simsong** [comment]
I will probably change the default build environment to AWS Linux.

**Comment by simsong** [comment]
OpenSSL 1.0 is the version that Amazon Linux has installed. I just did a clean install of AWS Linux and got this:
```
[ec2-user@ip-172-30-1-68 etc]$ sudo yum install openssl
Loaded plugins: priorities, update-motd, upgrade-helper
Package 1:openssl-1.0.2k-16.150.amzn1.x86_64 already installed and latest version
Nothing to do
[ec2-user@ip-172-30-1-68 etc]$
```

**Comment by fxcoudert** [comment]
From OpenSSL at https://www.openssl.org/policies/releasestrat.html :

> Version 1.0.2 will be supported until 2019-12-31 (LTS).
> Version 1.0.1 is no longer supported.

**Comment by simsong** [comment]
What OS has ssl 1.1? I tried amazon Linux, Centos 7, and Ubuntu LTS 18 yesterday and none of them gave me any problems.


----
Sent from my phone.

> On Nov 10, 2019, at 1:46 AM, FX Coudert <notifications@github.com> wrote:
> 

﻿
From OpenSSL at https://www.openssl.org/policies/releasestrat.html :

Version 1.0.2 will be supported until 2019-12-31 (LTS).
Version 1.0.1 is no longer supported.

**Comment by alebcay** [comment]
My Windows Subsystem for Linux (Debian Stretch) has OpenSSL 1.1.0l available:
```
caleb@LAPTOP-B7JL29P0:~$ sudo apt-cache policy openssl
openssl:
  Installed: 1.1.0l-1~deb9u1
  Candidate: 1.1.0l-1~deb9u1
  Version table:
 *** 1.1.0l-1~deb9u1 500
        500 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.0k-1~deb9u1 500
        500 http://deb.debian.org/debian stretch/main amd64 Packages
```

My other Debian box (Buster) has OpenSSL 1.1.1d available:
```
caleb@debian:~$ sudo apt-cache policy openssl
openssl:
  Installed: 1.1.1d-1+0~20191009.15+debian10~1.gbpd6badf
  Candidate: 1.1.1d-1+0~20191009.15+debian10~1.gbpd6badf
  Version table:
 *** 1.1.1d-1+0~20191009.15+debian10~1.gbpd6badf 500
        500 https://packages.sury.org/php buster/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.1d-0+deb10u2 500
        500 http://deb.debian.org/debian-security buster/updates/main amd64 Packages
     1.1.1c-1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
```

**Comment by simsong** [comment]
I just compiled bulk_extractor 1.6.0 on this OS release with no modifications, using OpenSSL 1.1.0:

```
admin@ip-172-30-1-20:~/bulk_extractor$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
admin@ip-172-30-1-20:~/bulk_extractor$ openssl version
OpenSSL 1.1.0l  10 Sep 2019
admin@ip-172-30-1-20:~/bulk_extractor$
```

It appears that OP is in error and that OpenSSL 1.1.0 is supported.

**Comment by simsong** [comment]
So if I spin up a debian box on AWS, you think I’ll get Buster? Is there an AMI you can point me at? If you can, I’ll make it work.
