### ISSUE TITLE
bulk_extractor does not build hashdb 3.1.0 support when hashdb is a static library

### ISSUE THREAD

**Issue by ptitdoc** [simsong/bulk_extractor#122]
Following this issue https://github.com/simsong/bulk_extractor/issues/89, hashdb 3.1.0 is apparently officially working.

However, running configure disable building hashdb because the version is apparently not present in the library:
```
checking hashdb.hpp usability... yes
checking hashdb.hpp presence... yes
checking for hashdb.hpp... yes
checking for hashdb_version in -lhashdb... no
configure: WARNING: Could not find hashdb library required to build the hashdb scanner
configure: the hashdb scanner will not be built
```
For some reason, hashdb is only static library on my system.
`
# ls -l /usr/lib/libhashdb.a
-rw-r--r-- 1 root root 2418250 Jan 31 13:29 /usr/lib/libhashdb.a
`

The line in configure.ac is :
https://github.com/simsong/bulk_extractor/blob/587a21952262686488eef5ea348cc8c24b22dbc5/configure.ac#L397

I will try to build hashdb as a shared library however I write this issue for documentation purpose.

**Comment by simsong** [comment]
Thank you for documenting this. I look forward to receiving your pull request!

**Comment by simsong** [comment]
I'm closing this, as I don't have the configure.log and have not received further info from @ptitdoc . Please re-open if this continues to be a problem.
