### ISSUE TITLE
Deprecation warning: <sys/sysctl.h> header is deprecated and will be removed

### ISSUE THREAD

**Issue by joachimmetz** [simsong/bulk_extractor#129]
Mainly FYI, building from HEAD (https://github.com/simsong/bulk_extractor/commit/bc5caa71e04906aeba387caff43c16017646d66f) gives me the following deprecation warning

```
In file included from main.cpp:53:
/usr/include/sys/sysctl.h:21:2: warning: #warning "The <sys/sysctl.h> header is deprecated and will be removed." [-Wcpp]
   21 | #warning "The <sys/sysctl.h> header is deprecated and will be removed."
      | 
```

**Comment by simsong** [comment]
On which platform?

**Comment by simsong** [comment]
Looks like the main use of `<sys/ctl.h>` is to figure out how many CPUs there are on the platform:

https://github.com/simsong/bulk_extractor/blob/ecb627d7b60d5a34b51639a8deaffc4db59fda27/src/threadpool.cpp#L39

Looks like there are new ways to figure out how many CPUs are present:
* https://stackoverflow.com/questions/150355/programmatically-find-the-number-of-cores-on-a-machine
* http://www.cplusplus.com/reference/thread/thread/hardware_concurrency/
* https://eli.thegreenplace.net/2016/c11-threads-affinity-and-hyperthreading/ (`cat /proc/cpuinfo`)

What's your preference?

**Comment by joachimmetz** [comment]
> On which platform?

Fedora 32 with glibc 2.31

Also see: https://sourceware.org/legacy-ml/libc-alpha/2019-08/msg00029.html they recoomend:
```
* The Linux-specific <sys/sysctl.h> header and the sysctl function have been
  deprecated and will be removed from a future version of glibc.
  Application should directly access /proc instead.  For obtaining random
  bits, the getentropy function can be used.
```
