### ISSUE TITLE
What is the latest release?

### ISSUE THREAD

**Issue by ryandesign** [simsong/bulk_extractor#147]
I would like to assume that the latest release is [1.6.0](https://github.com/simsong/bulk_extractor/releases/tag/v1.6.0) but the [main page of this github project](https://github.com/simsong/bulk_extractor) says the latest release is 1.5.3. It also says "This is the development tree. For downloads please see: http://downloads.digitalcorpora.org/downloads/" At that URL, the latest version available is 1.5.5, which [does not exist in this repository](https://github.com/simsong/bulk_extractor/issues/84). This is all very confusing.

**Comment by ryandesign** [comment]
If 1.6.0 is a valid release, then please create a GitHub release for it, describe the changes there, and upload to it a release tarball. The automatically-generated tarballs are not suitable because they do not contain the git submodules that you use.

**Comment by joachimmetz** [comment]
Based on https://forensicswiki.xyz/wiki/index.php?title=Bulk_extractor I would say 1.5.5 is the last release and 1.6.0 is current work-in-progress (or git HEAD).

**Comment by simsong** [comment]
Am currently working on 2.0 and it is expected by sept 30

**Comment by simsong** [comment]
I have updated Forensicswiki.

**Comment by simsong** [comment]
I have also deleted release 1.6.0 on the tag list. Thanks. I was working on 1.6.0 and we tagged it, and it is pretty good, but I did not complete the release process, so it is being pulled back. Version 2.0 will be the next release.
