### ISSUE TITLE
Error: unable to access jar file

### ISSUE THREAD

**Issue by suyashraut** [simsong/bulk_extractor#151]
![IMG_20200824_021456](https://user-images.githubusercontent.com/17405102/90988333-a6481200-e5af-11ea-9eba-57b5b3056e5c.jpg)
Whe I try to use command ./BEViewer it's says 
Error :Unable to access jarfile /home/Newton/Desktop/bulk_extractor-master/jav_gui/BEViewer.jar 
Later when I checked there was no BEViewer.jar file in java_gui . I think it has been removed by the provider . 
How could I now run beviewer . 
Please help !!!

**Comment by simsong** [comment]
I don't know who your provider is. Please properly install the program and then resubmit a proper bug report. Thanks!

**Comment by suyashraut** [comment]
I mean the BEViwere.jar file is not present inside java_gui filen

**Comment by simsong** [comment]
Well, you should see if it gets installed, and you should see if you have the proper version of Java. I recommend using a Linux distribution that has BE pre-installed, and I recommend not running BE from the Desktop. How did you install it? Why does your path say `bulk_extractor-master` ?

**Comment by suyashraut** [comment]
https://github.com/simsong/bulk_extractor
I have downloaded it from here . When I extracted it the extracted folder names bulk_extraction-master .
Can you please tell me the process how to install it on Linux . I am using it in a VM .

**Comment by simsong** [comment]
Please use one of the bulk extractor releases, not the git repo.
