### ISSUE TITLE
Better Unicode Support

### ISSUE THREAD

**Issue by simsong** [simsong/bulk_extractor#153]
See:
* https://stackoverflow.com/questions/48816848/what-is-the-efficient-standards-compliant-mechanism-for-processing-unicode-usin
* https://en.cppreference.com/w/cpp/locale/codecvt_utf8
* https://codingtidbit.com/2020/02/09/c17-codecvt_utf8-is-deprecated/
* https://stackoverflow.com/questions/215963/how-do-you-properly-use-widechartomultibyte
* https://stackoverflow.com/questions/23919515/how-to-convert-from-utf-16-to-utf-32-on-linux-with-std-library/65159352#65159352
* https://community.notepad-plus-plus.org/topic/15649/visualization-for-zero-width-characters
* https://chromium.googlesource.com/chromium/src/base/+/e54b164faf7ec01ecbaa5d59b289f0a5aeb51a09/strings/escape.cc
* http://gavinchou.github.io/experience/summary/unicode-summary/
* http://www.unicode.org/L2/L2002/02368-default-ignorable.pdf

**Comment by jonstewart** [comment]
Lightgrep has some utility functions for trying to decode context around a putative search hit according to a particular encoding.

https://github.com/strozfriedberg/lightgrep/blob/master/include/lightgrep/util.h

`lg_read_window()` will provide you an array of signed 32 bit integers that are Unicode code point values for the window. If some bytes fail to decode, they're signified as negative byte values.

`lg_read_context()` is more practical and will give you UTF-8 as output. Bytes that fail to decode will be replaced with the character of your choice.

Both use ICU.

**Comment by simsong** [comment]
Closing this, as 2.0 has pretty good unicode support at this point. Adding Lightgrep would be better, if Lightgrep is still operaitonal.
