### ISSUE TITLE
Use SIMD implementations for base16 and base64 scanners

### ISSUE THREAD

**Issue by jonstewart** [simsong/bulk_extractor#157]
x86 has had the pshufb instruction since the introduction of SSE3 in 2004. This instruction and later, more powerful variants are able to shuffle a vector of bytes according to a controlling input vector, typically in one cycle. It is often possible to use pshuf to implement optimized byte-wise lookup tables, and the performance delta between scalar algorithms and shuffle-based continues to grow with new micro architectures. 

http://0x80.pl/notesen/2016-01-17-sse-base64-decoding.html discusses several algorithms for decoding base64. Skylake CPUs using the AVX2 shuffle algorithms can decode base64 three times faster than the scalar version. 

ARM also has its own shuffle instruction.

**Comment by simsong** [comment]
Closing this, as it doesn't seem that we will be doing this.
