### ISSUE TITLE
Create unit test executable with Catch2

### ISSUE THREAD

**Issue by jonstewart** [simsong/bulk_extractor#164]
Create src/unittests and build specified Catch2 unit tests contained therein as a separate executable. Do likewise with Catch2 benchmarks.

**Comment by simsong** [comment]
How is this different from the current be_tests executable?

**Comment by jonstewart** [comment]
Yep, wrong branch.

**Comment by simsong** [comment]
OK. Let me know if you want to change the name. There are a lot of unit test that we need to incorporate.
