### ISSUE TITLE
Potentially erroneous exit statements in etc/CONFIGURE_UBUNTULTS18.bash

### ISSUE THREAD

**Issue by DataFrogman** [simsong/bulk_extractor#176]
File: https://github.com/simsong/bulk_extractor/blob/master/etc/CONFIGURE_UBUNTU18LTS.bash

The exit statement found on line 63 is unnecessary due to the failure check that immediately follows, furthermore it causes the script to exit with a code 1 whether or not the apt install succeeds.  The exit found on line 68 also terminates the script before the script can complete.  If these are not intended I can create a pull request to remove them.

**Comment by simsong** [comment]
Okay. Please submit a patch. Although we may just be taking this out.

**Comment by DataFrogman** [comment]
Addressed in https://github.com/simsong/bulk_extractor/pull/177

**Comment by DataFrogman** [comment]
During the update to 2.0 it appears that the bugs fixed in commits https://github.com/simsong/bulk_extractor/pull/177 and https://github.com/simsong/bulk_extractor/pull/175 were reintroduced.

**Comment by simsong** [comment]
They weren't re-introduced; the 2.0 fork happened before #177 and #175 were fixed! I'll apply them sometime today. Thanks.
