### ISSUE TITLE
fix offset for scan_zip so it counts from the PK and not from the zlib-compressed section

### ISSUE THREAD

**Issue by simsong** [simsong/bulk_extractor#200]
Output from BE16:
```
nps-2010-emails_be16/email.txt:456536-ZIP-0-MSXML-9     iwork09.comkeynote_comment@iwork09.com  \x0Akeynote@iwork09.comkeynote_comment@iwork09.com\x0A
nps-2010-emails_be16/email.txt:456536-ZIP-1255117       keynote@iwork09.com     nk href="mailto:keynote@iwork09.com?subject="><sf:s
nps-2010-emails_be16/email.txt:456536-ZIP-1255189       keynote@iwork09.com     racterStyle-38">keynote@iwork09.com</sf:span></sf:l
```

Output from BE20:

```
nps-2010-emails_be20v1/email.txt:456596-ZIP-0-MSXML-9   iwork09.comkeynote_comment@iwork09.com  \x0Akeynote@iwork09.comkeynote_comment@iwork09.com\x0A
nps-2010-emails_be20v1/email.txt:456596-ZIP-1255117     keynote@iwork09.com     nk href="mailto:keynote@iwork09.com?subject="><sf:s
nps-2010-emails_be20v1/email.txt:456596-ZIP-1255189     keynote@iwork09.com     racterStyle-38">keynote@iwork09.com</sf:span></sf:l
```

The BE forensic path |456536-ZIP-1255117| is read to mean that there is a feature that is located 1255117 bytes into a inflated ZIP stream that is itself located 456536 bytes from the beginning of the disk image. With the disk image nps-2010-emails, BE16 reported the ZIP stream beginning at 456536, but the current BE20 codebase reports the sameZIP stream beginning at location 456596. 

The 60-byte difference is the result of the ZIP header. BE20 correctly reports that the ZIP stream began at 456596 because the address was tracked automatically by the revised memory allocation routines that tracked the location of the sliced buffer that was handed to the decompressor. In BE16, the address was computed with explicit code, and that explicit code (rightly or wrongly) computed the location of the ZIP segment header,
rather than the ZLIB-deflated stream.

This is annoying as I try to make BE20 replicate BE16 behavior. In this case, the behavior is wrong. It would take extra code to replicate the wrong behavior. I guess I could create a flag to do that. Or I could just adjust in the analysis code, but that would be harder because the length of the offset is variable (depends on the filename).

@jonstewart - what do you think I should do?

Another issue is that there are probably too many command line options. Should we continue with them (easiest), or create a config file? I'm inlined to continue with them, simply because it's July 10 and I really want to finish this rewrite soon.

**Comment by jonstewart** [comment]
Bugs happen. Gotta fix ‘em! I keep a set of results from standard images for regression testing but when behavior changes, the result set changes. So I am +1 on the change. As you noted with DFXML, it is essential to associate a result set with the version of software used to produce it. A new version of bulk_extractor can then produce its own results to reflect greater accuracy/understanding.

With forensic paths, I do wonder whether they could be formatted as URI components. It’s not hard to imagine a little flask service someday in the future that could take such a path and then produce the data on demand.

RE: command line options, config files are nice and help support different SOPs and use cases. There are libraries in other languages that can provide command line arg parsing and config file support. I’d need to check on which ones are available for C++.


Jon

**Comment by simsong** [comment]
Okay, we fix and introduce a `be16-bug-compatible` mode for development purposes. 

meanwhile, I just enabled address sanitizer and it found a bug. I can’t wait to enable thread sanitizer.

**Comment by simsong** [comment]
This may not be necessary. I’m pretty happy with the zip scanner at this point

**Comment by simsong** [comment]
So I've thought about this more and now think that the BE16 mode is correct. The scanner uses and reports on the information after the PK, so the ZIP region, and not the deflate section. So I'll fix it and then we will get the identical output.

**Comment by simsong** [comment]
fixed.
