### ISSUE TITLE
enable codacity

### ISSUE THREAD

**Issue by simsong** [simsong/bulk_extractor#210]
c.f. https://github.com/sleuthkit/sleuthkit/issues/2472#issuecomment-886079493 per @joachimmetz

**Comment by joachimmetz** [comment]
@simsong is up to you, I've not found too much value in the service. A style guide with secure coding practices and CI on testing IMHO is more effective

**Comment by simsong** [comment]
Also, the main thing I am trying to do now is figure out a weird issue where I get a memory error when something is subclassed….
