### ISSUE TITLE
Fedora 32 autoconf -V = 2.69, cannot complete install without -V = 2.71

### ISSUE THREAD

**Issue by jdqw210** [simsong/bulk_extractor#218]
I'm now trying to manually update autoconf to 2.71, just putting this out there for those who need it

**Comment by simsong** [comment]
Yes, I have better luck with 2.71, bit many of the distributions have not been updated.

Do you use the GUI?

**Comment by jdqw210** [comment]
i'm on cli, was able to start the make process after fudging together autoconf 2.71, but after a bit it runs into this

`plugin_test.cpp: At global scope:
plugin_test.cpp:174:6: error: no declaration matches ‘void scanner_info::get_config(const string&, long long unsigned int*, const string&)’
  174 | void scanner_info::get_config(const std::string &n,unsigned long long *val,const std::string &help) {}
      |      ^~~~~~~~~~~~
`

**Comment by jdqw210** [comment]
may give ubuntu a shot just to see

**Comment by simsong** [comment]
I haven't tested the `master` release against `fedora32` but can do so. Right now all of my efforts are devoted to version 2.0. 

GitHub Actions doesn't have Fedora32 as a test environment, so it won't get tested as much.

**Comment by simsong** [comment]
Okay, I have Fedora32 running and will make sure that the master release works on fedora32 by the end of this weekend.

**Comment by jdqw210** [comment]
Hey I appreciate the effort. Thanks a lot

**Comment by jdqw210** [comment]
As an aside: I had the same stop at plugin_test.cpp:174:6 on ubuntu 18LTS

**Comment by simsong** [comment]
You don’t really need plugin_test, unless you are building plugins. You should be able to ‘cd’ into the ’src’ directory and just make from there.

**Comment by simsong** [comment]
Please try https://github.com/simsong/bulk_extractor/commit/1c67a759e12939ae9ccd0c3f1b7e275fdff74947 and let me know how it goes.
