### ISSUE TITLE
Remove extra autoremove in bulk_extractor/etc/CONFIGURE_UBUNTU20LTS.bash

### ISSUE THREAD

**Issue by Donovoi** [simsong/bulk_extractor#262]
Hi simsong,

I noticed that I was getting the following error when trying to run CONFIGURE_UBUNTU20LTS.bash on WSL2-Ubuntu 20.04.3 LTS, I was getting the  following (Non Fatal) error:

"E: Unable to locate package autoremove"

I believe this is because on line 57 we have a redundant "autoremove" see here:

sudo apt autoremove -y autoremove

After removing the second or first autoremove, I was able to run the script without error. 

Please be advised that this is one of my first issues, if it is in the wrong format I'm happy to change it. 

Also happy to submit pull request if you'd prefer. 

Thank you!

**Comment by simsong** [comment]
Looks like this has been resolved.
