### ISSUE TITLE
Capture CPU utilization in DFXML

### ISSUE THREAD

**Issue by simsong** [simsong/bulk_extractor#290]
It would be nice to graph CPU utilization over the course of the run solely from information in the dfxml file.
- [x] Add CPU load to the DFXML. 
- [ ] Back-port this to BE1.6 so that we can generate graphs of that as well.

**Comment by simsong** [comment]
> Gugzitz

??

**Comment by sevrb** [comment]
> > Gugzitz
> 
> ??

**Comment by sevrb** [comment]
Ghx

**Comment by simsong** [comment]
Don't think that this will be back-ported to 1.6.
