### ISSUE TITLE
Validate 2.0.0 on Windows

### ISSUE THREAD

**Issue by simsong** [simsong/bulk_extractor#344]

**Comment by kieranjol** [comment]
If this requires testing, I can help with this? Or do you need someone to actually build it?

**Comment by dursun0007** [comment]
Is there an installation package for windows?

**Comment by simsong** [comment]
Not yet.

**Comment by tomnewman86** [comment]
Tested and succesfully compiled a win64 executable this morning. 

Ran a quick test using BE on a sample pagefile.sys and it worked perfectly and rapidly! 

Fantastic work and thank you.

**Comment by simsong** [comment]
2.0.1 works on Windows. You can get a copy of it here:
https://digitalcorpora.s3.amazonaws.com/downloads/bulk_extractor/bulk_extractor-windows-2.0.1.zip

**Comment by dursun0007** [comment]
> 2.0.1 works on Windows. You can get a copy of it here: https://digitalcorpora.s3.amazonaws.com/downloads/bulk_extractor/bulk_extractor-windows-2.0.1.zip
download link for windows not working
