### ISSUE TITLE
Mingw cross-compiling for Win64 - error with scan_find.cpp

### ISSUE THREAD

**Issue by tomnewman86** [simsong/bulk_extractor#346]
Hi Simson,

I've just run into an error when cross-compiling for win64 in relation to **scan_find.cpp**

![image](https://user-images.githubusercontent.com/32235222/154280533-e06b3263-37a3-41f5-b04a-3cb63adc347a.png)

I hope this helps but happy to provide further info if required.

Thanks,

**Comment by simsong** [comment]
Correct. The cross compiling is currently broken. Thanks. I will try to fix soon. I have a VM spun up for the purpose.

**Comment by tomnewman86** [comment]
No worries at all. Apologies for posting anything you're already aware of.

**Comment by simsong** [comment]
No apologies necessary! I love the feedback.
