### ISSUE TITLE
Remove PHASE_ENABLED

### ISSUE THREAD

**Issue by jonstewart** [simsong/bulk_extractor#358]
scanner_params.h defines PHASE_ENABLED, inbetween PHASE_INIT2 and PHASE_SCAN, but scanners do not seem to be called with this phase. It really only seems to be used in `scanner_set.cpp` in the `be20_api` submodule.

What is `PHASE_ENABLED` for?

**Comment by simsong** [comment]
Apparently it is now being set but never used. It was previously used to let the scanners know that initialization was over, and all of the scanners would get a message that they were now enabled, and some did additional initialization. 

Now all of the scanners get called with PHASE_INIT2. After that, we are no longer in PHASE_INIT2, so it moves to PHASE_ENABLED. 

I think that it can be removed.

**Comment by simsong** [comment]
"If it aint broke, don't fix it." It seems to be working, so let's just leave it.
