### ISSUE TITLE
compiled windows executable does not have E01 compatibility

### ISSUE THREAD

**Issue by tomnewman86** [simsong/bulk_extractor#361]
Hi Simson,

I'm having issues when cross compiling bulk_extractor to the win64 executable. It doesn't appear to compile with E01 compatibility

![bulk_e01_error](https://user-images.githubusercontent.com/32235222/173397838-11dfe4a5-3ec8-40d9-99e2-2c23bb2fc6fe.png).

I've tested the linux binary which works with E01s fine so I believe it's isolated to the win64 executable or I'm not compiling it correctly.

I'd appreciate any support or guidance on this matter.

Thanks

**Comment by simsong** [comment]
How are you preparing the VM on which you are doing the compilation? Are you running our [prep script](https://github.com/simsong/bulk_extractor/blob/main/etc/CONFIGURE_FEDORA34.bash)? There are a _lot_ of modules that need to be installed.

**Comment by tomnewman86** [comment]
Cheers for the quick response.

The steps for compilation were as follows:

1. Cloned the git repo to Fedora 35 
2. Installed the submodules
3. Ran bootstrap.sh
4. Ran /src_win/CONFIGURE_FEDORA31.bash
5. Ran make win64
6. Copied bulk_extractor executable to windows machine and tested on E01

**Comment by simsong** [comment]
The prep script is:
https://github.com/simsong/bulk_extractor/blob/main/etc/CONFIGURE_FEDORA34.bash

Not  /src_win/CONFIGURE_FEDORA31.bash

Did you typo?

**Comment by tomnewman86** [comment]
> The prep script is: https://github.com/simsong/bulk_extractor/blob/main/etc/CONFIGURE_FEDORA34.bash
> 
> Not /src_win/CONFIGURE_FEDORA31.bash
> 
> Did you typo?

No this appears to be my mistake.

Are the instructions here -> https://github.com/simsong/bulk_extractor/wiki/Installing-bulk_extractor out of date? This is what I was following.

Let me retry with the up-to-date config script and report back

Thanks

**Comment by simsong** [comment]
Yes, that is out of date. Please feel free to update it.

**Comment by simsong** [comment]
Did you run on a clean VM, or one that you have used for other things?
Which version of Fedora did you use?
I need to modify the prep script to complain if libewf is not installed after it runs. Can you post your config.log here for me to review?

**Comment by tomnewman86** [comment]
Sorry for the delayed response. The VM has been spun up specifically for cross compiling BE so it should be clean. 

I'm running Fedora 35

Please see the attached config.log. You'll see at "configure:8767" it fails to get the libewf version and does not compile with E01 support although it seemingly finds libewf earlier in the compilation although I could be interepting that incorrectly. Take a look and see what you think.

Thanks

[config.log](https://github.com/simsong/bulk_extractor/files/8908603/config.log)

**Comment by nkl0x55** [comment]
Hi, I am facing a similar issue when using Fedora 36. The libewf appear to have issue.

![IMG_20230210_232229_219.PNG](https://user-images.githubusercontent.com/5791182/220583757-0baf01e1-8d98-412e-8e97-963baa6e574a.PNG)

**Comment by simsong** [comment]
Thanks for looking into this.
There is a new, updated version of libewf that handles SSL3.0.
Can you try this release?
https://github.com/libyal/libewf/releases/tag/20230212

Thank you.

**Comment by joachimmetz** [comment]
These changes should also be in the latest libewf stable https://github.com/libyal/libewf-legacy/releases/tag/20140814 what version is being used?

**Comment by simsong** [comment]
> Hi, I am facing a similar issue when using Fedora 36. The libewf appear to have issue.
> 
> ![IMG_20230210_232229_219.PNG](https://user-images.githubusercontent.com/5791182/220583757-0baf01e1-8d98-412e-8e97-963baa6e574a.PNG)

@nkl0x55  - are you trying to compile for Linux or cross-compile for Windows?

**Comment by nkl0x55** [comment]
@simsong Hi, was trying to cross compile for Windows.

Steps taken:

1. Prepare a fresh Fedora 36 VM
2. Ran the Fedora 36 script found in the etc folder
3. Encounter the error

**Comment by simsong** [comment]
Hi. The Fedora 36 script needs to be updated to use the more recent version of libewf. 

Can you try this release?
https://github.com/libyal/libewf/releases/tag/20230212

**Comment by nkl0x55** [comment]
Hi, I tried updating the etc/paths.bash file to point to https://github.com/libyal/libewf/releases/download/20230212/libewf-experimental-20230212.tar.gz

However, error still occurred.

Attached is the log that I save.
[installation.log](https://github.com/simsong/bulk_extractor/files/10815056/installation.log)

**Comment by simsong** [comment]
Hi, @nkl0x55 . It's easier for the maintainer (@joachimmetz ) if you post the actual error, which is here:
```
ewftools_output.c: In function ‘ewftools_output_version_detailed_fprint’:
ewftools_output.c:244:10: error: ‘SHLIB_VERSION_NUMBER’ undeclared (first use in this function); did you mean ‘SSLEAY_VERSION_NUMBER’?
  244 |          SHLIB_VERSION_NUMBER );
      |          ^~~~~~~~~~~~~~~~~~~~
      |          SSLEAY_VERSION_NUMBER
ewftools_output.c:244:10: note: each undeclared identifier is reported only once for each function it appears in
```
@joachimmetz  - this is cross-compiling on FC36 with mingw.  My guess is that `SHLIB_VERSION_NUMBER` doesn't exist when compiling as a linkable win32 library.

**Comment by joachimmetz** [comment]
That should not matter, it's a pre-compilation macro that gets translated into a string. 

It looks like installation.log uses CMake to build libewf and not autotools?

**Comment by joachimmetz** [comment]
Also installation.log indicates that you're still trying to build version 20201230

```
make[1]: Leaving directory '/home/kl/Downloads/bulk_extractor-main/etc/libewf-20201230/ewftools'
```

**Comment by joachimmetz** [comment]
Also installing libewf-legacy devel from the Fedora repo, can confuse the build process

```
 libewf                                                               x86_64                                          20140608-23.fc36                                                 fedora                                           552 k
 libewf-devel                                                         x86_64                                          20140608-23.fc36                                                 fedora                                            27 k
```

**Comment by joachimmetz** [comment]
also if you only need the library for cross-compilation why not use `make lib` instead of building everything ?

**Comment by simsong** [comment]
> also if you only need the library for cross-compilation why not use `make lib` instead of building everything ?

Didn’t know it was an option.

**Comment by simsong** [comment]
@joachimmetz  - what is the `make install` target to install just the library? Otherwise `make install` will cause everything to be made.

**Comment by joachimmetz** [comment]
Good question `make lib` is an alias for the autoconf generated `make library` so for install maybe `make install-libLTLIBRARIES`. I would need to do some experimentation

**Comment by joachimmetz** [comment]
Looks like `make library` is something I might added in the past. I can have a look to see if I can add a corresponding `make install-library` target

**Comment by simsong** [comment]
I have a PR that I think will build win32 with libewf, but the VM I was running it on wasn’t large enough.

https://github.com/simsong/bulk_extractor/pull/386

**Comment by simsong** [comment]
Okay, I was able to test #386 and it has a problem:
```
x86_64-w64-mingw32-g++ -std=c++17 -DHAVE_CONFIG_H -I. -I../../src -I..  -I../../src/be20_api -DUNICODE -D_UNICODE -D__MSVCRT_VERSION__=0x0601 -DWINVER=0x0500 -D_WIN32_WINNT=0x0500 -g  --static  -DUTC_OFFSET=+0000  -g -static-libstdc++  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4 -Wno-format  --static -static-libgcc -static-libstdc++ -pthread -Wall -MD -Wpointer-arith -Wshadow -Wwrite-strings -Wcast-align -Wredundant-decls -Wdisabled-optimization -Wfloat-equal -Wmultichar -Wmissing-noreturn -Woverloaded-virtual -Wsign-promo -funit-at-a-time -O3 -MT image_process.o -MD -MP -MF $depbase.Tpo -c -o image_process.o ../../src/image_process.cpp &&\
mv -f $depbase.Tpo $depbase.Po
../../src/image_process.cpp: In static member function 'static void process_ewf::local_e01_glob(std::filesystem::__cxx11::path, char***, int*)':
../../src/image_process.cpp:117:30: error: no matching function for call to 'std::__cxx11::basic_string<char>::basic_string(std::filesystem::__cxx11::path&)'
  117 |     std::string dirname(fname);
      |                              ^
```
What's weird here is that it looks like we are using C++11 std::filesystem, even though we are clearly compiling with C++17. I'm in a low-connectivity environment and this is a high-demand weekend. Nevertheless, if I can get this working this weekend, I'll create a .exe that people can download.

**Comment by simsong** [comment]
Okay, https://github.com/simsong/bulk_extractor/pull/386 now compiles and runs. However, the `test_be.exe` does not run under wine because of a pathname issue. Can anyone figure this out?
```
-----------------------------------------------------------------------------------------------------------------------
scan_winprefetch
-----------------------------------------------------------------------------------------------------------------------
../../src/test_be1.cpp:669
.......................................................................................................................

../../src/test_be1.cpp:127: FAILED:
  REQUIRE( std::filesystem::exists(dest)==true )
with expansion:
  false == true

test_be.cpp:map_file - "Z:\\home\\simsong\\bulk_extractor\\win64\\src\\tests\\testfilex.docx" does not exist.
Environment variables:
SHELL=/bin/bash
LESS=--RAW-CONTROL-CHARS
GREP_COLOR=1;30;40
HISTCONTROL=ignoreboth:erasedups
MP=kAxRSRlMJoFiE
HISTSIZE=1000
HOSTNAME=vultr.guest
SSH_AUTH_SOCK=/tmp/ssh-XXXX5TFqHb/agent.77740
HISTTIMEFORMAT=%F %T
ITERM_PREV_PS1=\[]133;D;$?0148:fixme:console:write_console beep
]133;A0148:fixme:console:write_console beep
\][vultr \w \t]\[\033[0;31m\](dev-win32)\[\e[0m\] \$ \[]133;B0148:fixme:console:write_console beep
\]
COPY_EXTENDED_ATTRIBUTES_DISABLE=1
EDITOR=emacs
ITERM_ORIG_PS1=[vultr \w \t]\[\033[0;31m\](dev-win32)\[\e[0m\] \$
NAME=
LOGNAME=simsong
XDG_SESSION_TYPE=tty
MANPATH=/opt/local/share/man:/opt/local/man/:/usr/local/man:
GREP_OPTIONS=--color=auto
XAUTHORITY=/home/simsong/.Xauthority
MOTD_SHOWN=pam
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=
01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.
zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz
=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.c
ab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01
;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.
m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;3
5:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01
;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opu
s=00;36:*.spx=00;36:*.xspf=00;36:
HADOOP_MAPRED_HOME=/usr/local/hadoop
PYTHONSTARTUP=/home/simsong/slg/dotfiles/pythonstartup.py
DELDIR=/home/simsong/.Trash
PROMPT_COMMAND=history -a; history -r; prompt_func;printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"; iterm2_preexec_invoke_cmd
SSH_CONNECTION=69.243.9.113 64006 149.28.43.0 22
HADOOP_COMMON_HOME=/usr/local/hadoop
MAKEFLAGS=-j1
XDG_SESSION_CLASS=user
SELINUX_ROLE_REQUESTED=
TERM=xterm-256color
HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
HADOOP_HOME=/usr/local/hadoop
LESSOPEN=||/usr/bin/lesspipe.sh %s
USER=simsong
HADOOP_HDFS_HOME=/usr/local/hadoop
SELINUX_USE_CURRENT_RANGE=
SHLVL=1
XDG_SESSION_ID=16
COPYFILE_DISABLE=1
XDG_RUNTIME_DIR=/run/user/1000
PS1=[vultr \w \t]\[\033[0;31m\](dev-win32)\[\e[0m\] \$
SSH_CLIENT=69.243.9.113 64006 22
DEBUGINFOD_URLS=https://debuginfod.fedoraproject.org/
which_declare=declare -f
LC_ALL=en_US.UTF-8
XDG_DATA_DIRS=/home/simsong/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
SELINUX_LEVEL_REQUESTED=
HISTIGNORE=pwd:ls:ls -ltr:
BLOCKSIZE=1k
HADOOP_YARN_HOME=/usr/local/hadoop
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
MAIL=/var/spool/mail/simsong
SSH_TTY=/dev/pts/0
HADOOP_PREFIX=/usr/local/hadoop
OLDPWD=/home/simsong/bulk_extractor/etc
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
_=/usr/bin/wine
ComSpec=C:\windows\system32\cmd.exe
NUMBER_OF_PROCESSORS=1
OS=Windows_NT
PATH=C:\windows\system32;C:\windows;C:\windows\system32\wbem;C:\windows\system32\WindowsPowershell\v1.0
PATHEXT=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=5e03
windir=C:\windows
winsysdir=C:\windows\system32
TEMP=C:\users\simsong\Temp
TMP=C:\users\simsong\Temp
APPDATA=C:\users\simsong\AppData\Roaming
CLIENTNAME=Console
HOMEDRIVE=C:
HOMEPATH=\users\simsong
LOCALAPPDATA=C:\users\simsong\AppData\Local
LOGONSERVER=\\VULTR
SESSIONNAME=Console
USERDOMAIN=VULTR
USERNAME=simsong
USERPROFILE=C:\users\simsong
ALLUSERSPROFILE=C:\ProgramData
ProgramData=C:\ProgramData
PUBLIC=C:\users\Public
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=VULTR
ProgramFiles=C:\Program Files
CommonProgramFiles=C:\Program Files\Common Files
WINEDATADIR=\??\Z:\usr\share\wine
WINEHOMEDIR=\??\Z:\home\simsong
WINECONFIGDIR=\??\Z:\home\simsong\.wine
WINEDLLDIR0=\??\Z:\usr\lib64\wine
WINESYSTEMDLLPATH=\??\Z:\usr\x86_64-w64-mingw32\sys-root\mingw\bin
WINELOADER=/usr/bin/wine64
WINEUSERNAME=simsong
WINEUSERLOCALE=en-US
SystemDrive=C:
SystemRoot=C:\windows
```

**Comment by simsong** [comment]
Works.
