### ISSUE TITLE
Do not compile in restart functionality when libexpat is not available.

### ISSUE THREAD

**Issue by SandySchoene** [simsong/bulk_extractor#375]
Recently I discovered an issue during the make part of the installation.

The following error code occured as output of the make operation:

```
bulk_extractor.cpp: In function ‘int bulk_extractor_main(std::ostream&, std::ostream&, int, char* const*)’:
bulk_extractor.cpp:486:22: error: no matching function for call to ‘bulk_extractor_restarter::restart()’
  486 |             r.restart();                    // load the restart file and rename report.xml
      |             ~~~~~~~~~^~
```

I solved this Problem by installaing libepad-dev on my system.

The Issue is, that the bulk_extractor_restarter. h file does not have a solution for systems, who dont have libexpad-dev installed.

**Comment by simsong** [comment]
Hi. This is really interesting. the program compiles with GitHub Actions. Can you tell me what OS you were compiling on, and how you installed `libexpad-dev`?

Do you mean `libexpat-dev` or `libexpat1-dev` ?

On FEDORA you need to install `expat-devel`:
https://github.com/simsong/bulk_extractor/blob/27e20ba2194cf9ce9390f42cb75fb73204be394c/etc/CONFIGURE_FEDORA36.bash#L45
How did you configure your VM?

**Comment by simsong** [comment]
@SandySchoene  - Can you tell me why libexpat was not available? Was this a choice? 
I'm going to close this ticket. Please re-open if the you think that there is a compelling reason to compile on a system without having libexpat.
