### ISSUE TITLE
Upload new BE 2.0 (EXE) for windows

### ISSUE THREAD

**Issue by dursun0007** [simsong/bulk_extractor#382]
2.0.1 works on Windows. You can get a copy of it here: https://digitalcorpora.s3.amazonaws.com/downloads/bulk_extractor/bulk_extractor-windows-2.0.1.zip
download link for windows not working

**Comment by simsong** [comment]
Here is the correct download directory:
https://downloads.digitalcorpora.org/downloads/bulk_extractor

Strangely, the 2.0 windows is missing.

**Comment by simsong** [comment]
Apparently the 2.0 for Windows hasn't gone through beta testing yet. Can you give it a try and let me know if it works for you?
https://github.com/simsong/bulk_extractor/releases/tag/v2.0.0-beta1

**Comment by randomaccess3** [comment]
Are there any plans to provide the compiled version of v2.0.0? 
I played with Beta 1 and it worked well for my use case, but I haven't looked at compiling the released version yet.

**Comment by simsong** [comment]
Hi. Thanks for the update. I've been really remiss on this. It shoudln't be hard, and I'm thinking of having the GitHub Actions system automatically build the EXE each time through. But I have been distracted on other things. Let me see if I can spin up a VM and get something out this week.

**Comment by simsong** [comment]
Can you give https://github.com/simsong/bulk_extractor/pull/386 a try?

**Comment by randomaccess3** [comment]
Sorry, not sure where to find the exe - have had a look around but not sure where actions packages it up

**Comment by simsong** [comment]
Okay. This is from a while ago. Do you have access to a Fedora system?  if not, I can make a .exe for you to try.

**Comment by randomaccess3** [comment]
Nah, won't have a chance for a while to go through the build process. Am using the beta1 exes thats out of releases and seems to be working fine.
Will have to look at how to easily get stuff built when I've got some breathing space.

**Comment by simsong** [comment]
I can make one for you tonight if you can test it.

**Comment by simsong** [comment]
Hi @randomaccess3  - do you have the ability to test an executable?

**Comment by randomaccess3** [comment]
I haven't yet sorry. I will soon!

**Comment by simsong** [comment]
I have posted V2 for windows.
