### ISSUE TITLE
2.0.3 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [simsong/bulk_extractor#407]
👋 it looks like 2.0.3 release was not completed, ie `bulk_extractor-2.0.3.tar.gz` artifact is not available for package manager to use. :)

**Comment by simsong** [comment]
Correct. I got compiler warnings.

**Comment by simsong** [comment]
Where would you like it?

**Comment by simsong** [comment]
https://digitalcorpora.s3.amazonaws.com/downloads/bulk_extractor/bulk_extractor-2.0.3.tar.gz
