### ISSUE TITLE
Bulk_extractor

### ISSUE THREAD

**Issue by Hijackkked** [simsong/bulk_extractor#461]

**Comment by Hijackkked** [comment]
-https://github.com/simsong/bulk_extractor/assets/155051135/a072fc7a-5f4e-429d-a9b9-61f392a3bcac

**Comment by simsong** [comment]
<img width="1150" alt="Screenshot 2024-02-20 at 2 45 05 PM" src="https://github.com/simsong/bulk_extractor/assets/1594284/04937897-2a99-487e-8528-dbb2401eead0">
