### ISSUE TITLE
bootstrap.sh not present in bulk_extractor-1.4.1.tar.gz 

### ISSUE THREAD

**Issue by dkovar** [simsong/bulk_extractor#47]
The README references bootstrap.sh for OS X but that file isn't present in the distribution.

configure/make builds a working version, so this isn't a major issue.

-David

**Comment by schmiedecker** [comment]
./configure is also missing in the 1.5.3 release at https://github.com/simsong/bulk_extractor/archive/v1.5.3.tar.gz
