### ISSUE TITLE
Scanning in recursive mode drops features and files

### ISSUE THREAD

**Issue by BruceMty** [simsong/bulk_extractor#70]
When running the bulk_extractor in recursive directory scan mode (-R), bulk_extractor drops features and files:
- If a feature is encountered but a feature has already been recorded at that Forensic Path from another file, then the feature is dropped.
- If a filename is not simple ASCII, bulk_extractor will skip the file and not scan it.

This behavior limits completeness of scans using recursive mode.

**Comment by simsong** [comment]
I need a test case for this. Since the forensic path depends on the filename, I don't see how a feature found in one file could have the same forensic path as a feature found in another. I'm closing this until @BruceMty can provide a test case.
