### ISSUE TITLE
java_gui/src/image/ImageReaderManager.java is missing

### ISSUE THREAD

**Issue by uckelman** [simsong/bulk_extractor#72]
ImageReaderManager.java is missing in 3df29f7e0b09a59fff82d2bead7bb8406dcf08cc, which is HEAD at present:

    [uckelman@scylla java_gui]$ make
    make: *** No rule to make target `src/image/ImageReaderManager.java', needed by `BEViewer.jar'. Stop.

**Comment by BruceMty** [comment]
src/image/ImageReaderManager.java has been removed but the dependency is still in the Makefile.  Please run bootstrap.sh.  That should clear it up.

**Comment by uckelman** [comment]
Oh. Sorry, apparently I had a stale java_gui/Makefile.
