### ISSUE TITLE
403 Forbidden error when accessing download link

### ISSUE THREAD

**Issue by gtback** [simsong/bulk_extractor#77]
I'm getting a `403 Forbidden` error when accessing http://digitalcorpora.org/downloads/bulk_extractor. I was unable to access the entire digitalcorpora.org site yesterday, so perhaps this is a residual result of that.

Alternatively, GitHub's "Releases" feature could be used to host source archives (even if the archives are more than just zipped archives of a given tag in the repo).

**Comment by simsong** [comment]
Perhaps we should move digitalcorpora.org back to dreamhost.

**Comment by BruceMty** [comment]
I have seen this periodically, and have always seen digitalcorpora back up after a few hours.

**Comment by simsong** [comment]
fixed.
