### ISSUE TITLE
Tag version 1.5.5

### ISSUE THREAD

**Issue by gtback** [simsong/bulk_extractor#84]
I noticed there's no tag for 1.5.5, corresponding to the download available from http://digitalcorpora.org/downloads/bulk_extractor/bulk_extractor-1.5.5.tar.gz .

Perhaps this commit? 85471cfbc94f97a8117b2c68d6d6dba7ea7f0ab0

**Comment by juju4** [comment]
Hello,

Would be nice to have it, especially as digitalcorpora.org seems to have been reseted and above link is 404.

Thanks

**Comment by simsong** [comment]
We are transitioning the site.

**Comment by aei4n6** [comment]
Facelift time :)

**Comment by simsong** [comment]
Try http://downloads.digitalcorpora.org/downloads/bulk_extractor/

**Comment by ryandesign** [comment]
So, it's been over a year... how about finally creating the tag for 1.5.5?

**Comment by simsong** [comment]
It's been over a year, but little work has been done. What would you like to see done?

**Comment by ryandesign** [comment]
We would like to see a git tag that corresponds to the contents of [bulk_extractor 1.5.5](http://downloads.digitalcorpora.org/downloads/bulk_extractor/bulk_extractor-1.5.5.tar.gz) which was released three years ago.

**Comment by simsong** [comment]
Done.
```
(base) simsong@nimi bulk_extractor % git push --tags                                                                                    (master)bulk_extractor
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 162 bytes | 162.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:simsong/bulk_extractor.git
 * [new tag]         85471cf -> 85471cf
(base) simsong@nimi bulk_extractor %                                                                                                    (master)bulk_extractor
```

**Comment by gtback** [comment]
It looks like the tag is [named](https://github.com/simsong/bulk_extractor/releases/tag/85471cf)  `85471cf`.

**Comment by simsong** [comment]
You are right.
