### ISSUE TITLE
Using Carving with regular expressions

### ISSUE THREAD

**Issue by sarcarx** [simsong/bulk_extractor#86]
When using bulk_extractor with "-F custom_word_list", is the carving done on files that contain these expressions or is it done on every files? 
If I disable zip carving with "-S unrar_carve_mode=0", will bulk_extractor still analyse zip files for the wordlist?
I would like to obtain all the files that contain these regular expressions, what is the most suitable way of doing it?

Thanks for your answers.

**Comment by simsong** [comment]
Please review pp. 30 & 31 of the User's manual at http://digitalcorpora.org/downloads/bulk_extractor/BEUsersManual.pdf <http://digitalcorpora.org/downloads/bulk_extractor/BEUsersManual.pdf> .

The results of the wordlist hits are stored in the find.txt. ZIP file carving creates files that are carved out of ZIP files. The two features are unrelated.  RAR carving is different than ZIP carving. If the files are not carved they will still be scanned unless the corresponding scanners are disabled.

**Comment by sarcarx** [comment]
Ok thanks for your clear answer.

**Comment by sarcarx** [comment]
What about if I disable the zip scanner (I don't want the zip.txt file to be populated) but still want to search keywords in zip.
Does -x zip will achieve that? Or should I keep the zip scanner activated?

**Comment by sarcarx** [comment]
Also is there a way to make an insensitive case search with bulk_extractor?

**Comment by simsong** [comment]
Please read the manual and try experimenting with tiny disk images.


----

**Comment by sarcarx** [comment]
OK it is written that the SCANNER_RECURSE flag indicates that the scanner should be activated for bulk_extractor to search within analyzed data.
What about case insensitive search?

**Comment by simsong** [comment]
Thanks for reading the manual!

Case insensitive in which language?  Are you assuming you are dealing with 7-bit ASCII characters? 

I think that your best bet is to use regular expressions that are case insensitive.
