### ISSUE TITLE
omitting files of size or by path

### ISSUE THREAD

**Issue by abrin** [simsong/bulk_extractor#87]
apologies if this is a dup or if I missed something in the manual, but we're trying to run bulk_extractor on a directory tree of over 5 million files and there are a few issues we're hitting:

1. it freezes? on a massive 500GB zip file and we've had to kill it after 5 days (telling it to skip big zip files helps, along with not carving

2. it also seems to freeze? on similarly large txt files.

I've tried ``bulk_extractor -R /tdar-root/filestore -o /tdar-scratch/09162026 -S jpeg_carve_mode=0  -S zip_max_uncompr_size=10000 -S zip_carve_mode=0 `` 

Does the max_uncompr_size mean that it's going to try and uncompress the zip? is there a way to just ignore the zip format, or pass in a large list of files like you could a TAR?

thanks

**Comment by simsong** [comment]
Try turning off the ZIP scanner.

How much RAM is on your system? It sounds like you need more.

**Comment by abrin** [comment]
Thanks for the response.  Turning off the ZIP scanner helped with the zip file, but not the associated big text file.  We definitely are RAM constrained. I've ultimately broken the directory into lots of small directories and scanned them separately, which did work.  It'd be nice to have more control over what I scan and what I don't though either with a list of files, or more granular set of ignores.

**Comment by simsong** [comment]
How much RAM does your computer have? In general, it does not make sense to commit engineering effort to solutions that are caused by people running the software on underpowered computers.

**Comment by abrin** [comment]
We have 8GB or RAM total on the machine.

**Comment by simsong** [comment]
Well, that's pretty light for a digital forensics machine. You can get 256GB upgrades for Mac Pros and Dell towers for under $1000. A SuperMicro machine with 64 cores and 768GB of RAM costs under $10,000. I believe that you will find that these prices compare favorably with a week's work of developer time.
