### ISSUE TITLE
How do I use the python bindings?

### ISSUE THREAD

**Issue by estuart** [simsong/bulk_extractor#88]
I have compiled bulk extractor and am attempting to use the python bindings. I am unable to find `libbulkextractor.so`. In the documentation it mentions that I will have to build the python extension myself.

Could you provide instruction on how I would go about doing that or point me to a resource?

Thanks!

**Comment by simsong** [comment]
The library is one of the targets in the src/ directory. You should be able to build it by typing "make". 

Please write up your experience with the python bindings. I am not aware of anyone other than the original developer who has ever attempted to use it.

**Comment by estuart** [comment]
Looks like going in to /src and typing `make libs` did the trick. Thanks!

Right now I am experimenting with the idea of integrating Bulk Extractor as a module within the [LaikaBOSS object scanning system](https://github.com/lmco/laikaboss). I will be sure to report back my experience.

**Comment by simsong** [comment]
Let me know if I can be of any help.
