### ISSUE TITLE
integrate new libewf

### ISSUE THREAD

**Issue by simsong** [simsong/bulk_extractor#92]

**Comment by joachimmetz** [comment]
For now I recommend sticking with https://github.com/libyal/libewf-legacy

**Comment by simsong** [comment]
Really?

**Comment by joachimmetz** [comment]
Yes, wait until the API of the new version has been finalized.

**Comment by simsong** [comment]
We are using:
```
      <library name="libewf" version="20201230"/>
```
It seems fine, so I'm closing this ticket.
