### ISSUE TITLE
hi Unable to compile

### ISSUE THREAD

**Issue by xinjijia** [simsong/bulk_extractor#95]
not configure file

**Comment by simsong** [comment]
You need to create it with the bootstrap program.

**Comment by xinjijia** [comment]
hi,
Administrator@SER /cygdrive/c/Users/Administrator/Desktop/bulk_extractor-master/bulk_extractor-master
$ bootstrap
-bash: bootstrap: 未找到命令

Administrator@SER /cygdrive/c/Users/Administrator/Desktop/bulk_extractor-master/bulk_extractor-master
$ ./bootstrap
-bash: ./bootstrap: No such file or directory

**Comment by simsong** [comment]
I suggest you read the documentation. bootstrap.sh is a shell script in the root directory that runs autoconf.

**Comment by xinjijia** [comment]
root@bogon:/home/xin/bulk_extractor-master# ./bootstrap.sh
bringing in submodules
next time check out with git clone --recursive
./bootstrap.sh: 10: ./bootstrap.sh: git: not found
./bootstrap.sh: 11: ./bootstrap.sh: git: not found
bringing in submodules
next time check out with git clone --recursive
./bootstrap.sh: 10: ./bootstrap.sh: git: not found
./bootstrap.sh: 11: ./bootstrap.sh: git: not found
./bootstrap.sh: 17: ./bootstrap.sh: autoheader: not found
./bootstrap.sh: 20: ./bootstrap.sh: aclocal: not found
./bootstrap.sh: 21: ./bootstrap.sh: autoconf: not found
./bootstrap.sh: 23: ./bootstrap.sh: automake: not found

The bootstrap.sh is complete. Be sure to run ./configure.

**Comment by simsong** [comment]
Hi. I really think that you need to read the instructions, and learn how to build from sources. I can't teach you how to do that here. Compiling bulk_extractor from sources is complicated. You need to install the prerequisite to create the Makefile, or you need to download the ready-built sources and compile them, or you need to download pre-compiled executables. You should probably learn open source programs on an easier program. If you are just looking to run bulk_extractor, I suggest you get one of the existing open source Linux digital forensics distributions.

**Comment by xinjijia** [comment]
thanks
